<?php
require 'db.php';
$conn = conexion();

$view1 = "ALTER ALGORITHM=UNDEFINED DEFINER=`admin`@`localhost` SQL SECURITY DEFINER VIEW `guia_nota_venta_lista` AS select `a`.`id_guia` AS `id_guia`,`a`.`origen_guia` AS `origen_guia`,`a`.`destino_guia` AS `destino_guia`,`a`.`estado_guia` AS `estado_guia`,`a`.`total_guia` AS `total_guia`,`a`.`fecha_guia` AS `fecha_guia`,`a`.`fecha_creacion_guia` AS `fecha_creacion_guia`,`a`.`estado_guia_seguimiento` AS `estado_guia_seguimiento`,`a`.`estado_entregado_guia` AS `estado_entregado_guia`,`a`.`id_fkusuario_guia` AS `id_fkusuario_guia`,(case when ((`e`.`nombre_usuario` is not null) and (`e`.`apellido_usuario` is not null)) then concat(`e`.`nombre_usuario`,' ',`e`.`apellido_usuario`) else ' ' end) AS `usuarioguia`,`m`.`id_fkguia_despacho_detalle` AS `id_fkguia_despacho_detalle`,`a`.`estado_cobro_guia` AS `estado_cobro_guia`,`a`.`cedula_cliente_remitente` AS `cedula_cliente_remitente`,`a`.`nombre_cliente_remitente` AS `nombre_cliente_remitente`,`a`.`cedula_cliente_receptor` AS `cedula_cliente_receptor`,`a`.`nombre_cliente_receptor` AS `nombre_cliente_receptor`,`f`.`punto_emision_sucursal` AS `punto_emision_sucursal`,`a`.`punto_emision_guia` AS `punto_emision_guia`,`a`.`numero_guia` AS `numero_guia`, `a`.`numero_manual_guia` AS `numero_manual_guia`, coalesce(`h`.`monto_comprobante_cobro`,0) AS `cobrado`,(coalesce(`a`.`total_guia`,0) - coalesce(`h`.`monto_comprobante_cobro`,0)) AS `por_cobrar` from ((((`guia_nota_venta` `a` join `usuario` `e` on((`a`.`id_fkusuario_guia` = `e`.`id_usuario`))) join `sucursal2` `f` on((`a`.`sucursal_guia` = `f`.`suc_codigo_sucursal`))) left join `despacho_detalle` `m` on((`m`.`id_fkguia_despacho_detalle` = `a`.`id_guia`))) left join (select `comprobante_cobro_nota_venta`.`id_fkfactura_comprobante_cobro` AS `id_fkguia`,sum(`comprobante_cobro_nota_venta`.`monto_comprobante_cobro`) AS `monto_comprobante_cobro` from `comprobante_cobro_nota_venta` where (`comprobante_cobro_nota_venta`.`estado_comprobante_cobro` = 'COBRADA') group by `comprobante_cobro_nota_venta`.`id_fkfactura_comprobante_cobro`) `h` on((`h`.`id_fkguia` = `a`.`id_guia`)))";

mysqli_query($conn, $view1);
echo mysqli_error($conn) . "\n";

$view2 = "ALTER ALGORITHM=UNDEFINED DEFINER=`admin`@`localhost` SQL SECURITY DEFINER VIEW `guia_lista` AS select `a`.`id_guia` AS `id_guia`,`a`.`origen_guia` AS `origen_guia`,`a`.`destino_guia` AS `destino_guia`,`a`.`estado_guia` AS `estado_guia`,`a`.`total_guia` AS `total_guia`,`a`.`fecha_guia` AS `fecha_guia`,`a`.`fecha_creacion_guia` AS `fecha_creacion_guia`,`a`.`estado_guia_seguimiento` AS `estado_guia_seguimiento`,`a`.`estado_entregado_guia` AS `estado_entregado_guia`,`a`.`id_fkusuario_guia` AS `id_fkusuario_guia`,(case when ((`e`.`nombre_usuario` is not null) and (`e`.`apellido_usuario` is not null)) then concat(`e`.`nombre_usuario`,' ',`e`.`apellido_usuario`) else ' ' end) AS `usuarioguia`,`m`.`id_fkguia_despacho_detalle` AS `id_fkguia_despacho_detalle`,`a`.`estado_cobro_guia` AS `estado_cobro_guia`,`a`.`cedula_cliente_remitente` AS `cedula_cliente_remitente`,`a`.`nombre_cliente_remitente` AS `nombre_cliente_remitente`,`a`.`cedula_cliente_receptor` AS `cedula_cliente_receptor`,`a`.`nombre_cliente_receptor` AS `nombre_cliente_receptor`,`f`.`punto_emision_sucursal` AS `punto_emision_sucursal`,`a`.`punto_emision_guia` AS `punto_emision_guia`,`a`.`numero_guia` AS `numero_guia`, `a`.`numero_manual_guia` AS `numero_manual_guia`, coalesce(`h`.`monto_comprobante_cobro`,0) AS `cobrado`,(coalesce(`a`.`total_guia`,0) - coalesce(`h`.`monto_comprobante_cobro`,0)) AS `por_cobrar` from (((((`guia` `a` join `usuario` `e` on((`a`.`id_fkusuario_guia` = `e`.`id_usuario`))) join `sucursal2` `f` on((`a`.`sucursal_guia` = `f`.`suc_codigo_sucursal`))) left join `despacho_detalle` `m` on((`m`.`id_fkguia_despacho_detalle` = `a`.`id_guia`))) left join `factura` `b` on(((`b`.`id_fkguia_factura` = `a`.`id_guia`) and (`b`.`estado_factura` in (1,4))))) left join (select `comprobante_cobro`.`id_fkfactura_comprobante_cobro` AS `id_fkfactura_comprobante_cobro`,sum(`comprobante_cobro`.`monto_comprobante_cobro`) AS `monto_comprobante_cobro` from `comprobante_cobro` where (`comprobante_cobro`.`estado_comprobante_cobro` = 'COBRADA') group by `comprobante_cobro`.`id_fkfactura_comprobante_cobro`) `h` on((`h`.`id_fkfactura_comprobante_cobro` = `b`.`id_factura`)))";

mysqli_query($conn, $view2);
echo mysqli_error($conn) . "\n";
echo "Views updated\n";
?>
